--- 
- hosts: localhost
  connection: local
  become: true
  become_user: root
  tasks:

  - name: create {{download_dir}} 
    file: name={{download_dir}} 
          state=directory 
    tags: setup_download_dir

  - name: get CentOS 7 minimal
    get_url: url={{centos_min_url}}
             dest={{centos_min_file}}   
    tags: get_centos_min

  - name: install dhcp tftp tftp-server syslinux wget httpd
    yum: name={{item}}
    with_items:
    - dhcp 
    - tftp 
    - tftp-server 
    - syslinux 
    - wget 
    - httpd
    tags:
    - install_all

  - name: configure dhcp server
    lineinfile: name=/etc/dhcp/dhcpd.conf
        regexp="{{item}}"
        line="{{item}}"
        insertafter=EOF
        create=yes
    with_items:
    - 'ddns-update-style interim;'
    - 'ignore client-updates;'
    - 'authoritative;'
    - 'allow booting;'
    - 'allow bootp;'
    - 'allow unknown-clients;'
    - '# A slightly different configuration for an internal subnet.'
    - 'subnet 10.0.0.0 netmask 255.255.255.0 {'
    - '  range 10.0.0.200 10.0.0.253;'
    - '  option domain-name-servers 10.0.2.3;'
    - '  option domain-name \"cluster.bentley.edu\";'
    - '  option routers 10.0.2.2;'
    - '  option broadcast-address 10.0.0.199; #not important'
    - '  default-lease-time 600;'
    - '  max-lease-time 7200;'
    - '  # PXE SERVER IP'
    - '  next-server 10.0.0.100; #  DHCP server ip'
    - '  filename \"pxelinux.0\";'
    - '  host blade-201 {'
    - '   #hardware ethernet    08:00:07:26:c0:a5;'
    - '    hardware ethernet    08:00:27:91:DE:6B;'
    - '    fixed-address        10.0.0.201;'
    - '    option host-name     \"blade-201.cluster.bentley.edu\";'
    - '  } # host'
    - '} # subnet'
    tags: setup_dhcp

  - name: turn on tftp server
    lineinfile: name=/etc/xinetd.d/tftp
                regexp="disable"
                line="        disable = no" 
    tags: 
    - setup_tftp

  - name: adduser tftpd
    user: name=tftpd
    tags: 
    - setup_tftp

  - name: create directories
    file: path={{item}}
          mode=0777
          owner=tftpd
          group=tftpd
          state=directory
    with_items:
    - /var/lib/tftpboot
    - /var/lib/tftpboot/centos7_x64
    - /var/lib/tftpboot/pxelinux.cfg
    - /var/lib/tftpboot/netboot
    tags:
    - setup_tftp

  - name: put files to /var/lib/tftpboot/
    copy: src="/usr/share/syslinux/{{item}}"
          dest=/var/lib/tftpboot/
    with_items:
    - "pxelinux.0"
    - "menu.c32"
    - "memdisk"
    - "mboot.c32"
    - "chain.c32"
    tags: 
    - setup_tftp

  - name: mount iso file
    mount: src={{centos_min_file}}
           name=/mnt/
           fstype=iso9660
           state=mounted
    tags: 
    - setup_tftp

  - name: put files to /var/lib/tftpboot/netboot/
    copy: src="/mnt/images/pxeboot/{{item}}"
          dest=/var/lib/tftpboot/netboot
    with_items:
    - "vmlinuz"
    - "initrd.img"
    tags: 
    - setup_tftp
    - go 

    # "mkdir -p /var/lib/tftpboot/netboot/"

  - name: copy iso files
    copy: src=/mnt/
          dest=/var/lib/tftpboot/centos7_x64
          mode=0755
    tags:
    - setup_tftp

  - name: configure apache server
    lineinfile: name=/etc/httpd/conf.d/pxeboot.conf
        regexp="{{item}}"
        line="{{item}}"
        insertafter=EOF
        create=yes
    with_items:
    - 'Alias /centos7_x64 /var/lib/tftpboot/centos7_x64/'
    - '<Directory /var/lib/tftpboot/centos7_x64>'
    - 'Options Indexes FollowSymLinks'
    - 'Order Deny,Allow'
    - 'Deny from all'
    - 'Allow from 127.0.0.1 10.0.0.0/24'
    - '</Directory>'
    tags: setup_tftp

  - name: configure apache server
    lineinfile: name=/var/lib/tftpboot/pxelinux.cfg/default 
        regexp="{{item}}"
        line="{{item}}"
        insertafter=EOF
        create=yes
    with_items:
    - 'default menu.c32'
    - 'prompt 0'
    - 'timeout 300'
    - 'ONTIMEOUT local'
    - 'menu title PXE Boot Menu '
    - 'label 1'
    - 'menu label ^1\) Install CentOS 7'
    - 'kernel centos7_x64/images/pxeboot/vmlinuz'
    - 'append initrd=centos7_x64/images/pxeboot/initrd.img method=http://10.0.0.100/centos7_x64 devfs=nomount'
    - 'label 2'
    - 'menu label ^2\) Boot from local drive localboot'
    - 'label 3'
    - 'menu label ^3\) Kickstart'
    - 'kernel centos7_x64/images/pxeboot/vmlinuz'
    - 'append initrd=centos7_x64/images/pxeboot/initrd.img method=http://10.0.0.100/centos7_x64 ks=http://10.0.0.100/centos/ks.cfg'
    tags: 
    - setup_tftp
    - go

  - name: configure kickstart
    lineinfile: name=/var/lib/tftpboot/ks.cfg
        regexp="{{item}}"
        line="{{item}}"
        insertafter=EOF
        create=yes
    with_items:
    - 'default menu.c32'
    tags: 
    - setup_tftp

