--- 
- hosts: localhost
  connection: local
  become: true
  become_user: root 
  vars_prompt: 
 
  - name: "r_user_name" 
    prompt: "Enter a name for the R user"     
    private: yes     
    confirm: yes     
 
  - name: "r_user_password"     
    prompt: "Enter a password for the R user"     
    private: yes     
    encrypt: "md5_crypt"  
    confirm: yes     
    salt_size: 7 

  - name: "hadoop_password"     
    prompt: "Enter a password for user hadoop"     
    private: yes     
    encrypt: "md5_crypt"  
    confirm: yes     
    salt_size: 7 

  - name: "hdfs_password"     
    prompt: "Enter a password for user hdfs"
    private: yes     
    encrypt: "md5_crypt"  
    confirm: yes     
    salt_size: 7 

  tasks:

  - name: store R user account name
    lineinfile: name=/etc/ansible/vars.yaml
                regexp="r_user_name" 
                line="r_user_name{{colon}} {{r_user_name}}"
                create=yes

  - name: store R user account password (encryped)
    lineinfile: name=/etc/ansible/vars.yaml
                regexp="r_user_password" 
                line="r_user_password{{colon}} {{r_user_password}}"

  - name: store hadoop account password (encryped)
    lineinfile: name=/etc/ansible/vars.yaml
                regexp="hadoop_password" 
                line="hadoop_password{{colon}} {{hadoop_password}}"

  - name: store hdfs account password (encryped)
    lineinfile: name=/etc/ansible/vars.yaml
                regexp="hdfs_password" 
                line="hdfs_password{{colon}} {{hdfs_password}}"

# DONE
