---

# hosts: spark_master_host
- hosts: spark_master_host
  become: true
  become_user: root
  tasks:

  - name: start spark master
    command: "{{spark_dir}}/sbin/start-master.sh"
    tags: start_spark_master

  - name: stop spark master
    command: "{{spark_dir}}/sbin/stop-master.sh"
    tags: stop_spark_master

# hosts: spark_worker_hosts
- hosts: spark_worker_hosts
  become: true
  become_user: root
  tasks:

  - name: start spark workers
    command: "{{spark_dir}}/sbin/start-slave.sh {{spark_master_url}}"
    tags: start_spark_workers

  - name: stop spark workers
    command: "{{spark_dir}}/sbin/stop-slave.sh"
    tags: stop_spark_workers

# hosts: cassandra_seed_hosts
- hosts: cassandra_seed_hosts
  become: true
  become_user: root 
  tasks:

  - name: service cassandra (dsc) start (for seed nodes)
    service: name=cassandra
             state=started
    tags: start_dsc_seeds

  - name: service dse start (for seed nodes)
    service: name=dse
             state=started
    tags: start_dse_seeds

  - name: wait before starting the next node
    pause: seconds=30
    tags: start_dse_seeds,start_dsc_seeds

  - name: service dsc (cassandra) stop (for seed nodes)
    service: name=cassandra
             state=stopped
    tags: stop_dsc_seeds

  - name: service dse stop (for seed nodes)
    service: name=dse
             state=stopped
    tags: stop_dse_seeds

# hosts: cassandra_nonseed_hosts
- hosts: cassandra_nonseed_hosts
  become: true
  become_user: root 
  serial: 1
  tasks:

  - name: service dsc (cassandra) start (for non-seed nodes)
    service: name=cassandra
             state=started
    #until: wait_for port=9042
    tags: start_dsc_nonseeds

  - name: pause
    local_action: wait_for host={{inventory_hostname}} port=9042
    tags: start_dsc_nonseeds

  - name: service dse start (for non-seed nodes)
    service: name=dse
             state=started
    tags: start_dse_nonseeds

  - name: service dsc (cassandra) stop (for non-seed nodes)
    service: name=cassandra
             state=stopped
    tags: stop_dsc_nonseeds

  - name: service dse stop (for non-seed nodes)
    service: name=dse
             state=stopped
    tags: stop_dse_nonseeds

# hosts: hdfs_namenode_host
- hosts: hdfs_namenode_host
  become: true
  become_user: root
  tasks:

  - name: service hadoop-hdfs-namenode start
    service: name=hadoop-hdfs-namenode
             state=started
             enabled=yes
    tags: start_hdfs_namenode

  - name: service hadoop-hdfs-namenode stop 
    service: name=hadoop-hdfs-namenode
             state=stopped
    tags: stop_hdfs_namenode

# hosts: hdfs_datanode_hosts
- hosts: hdfs_datanode_hosts
  become: true
  become_user: root
  tasks:

  - name: service hadoop-hdfs-datanode start 
    service: name=hadoop-hdfs-datanode 
             state=started
    tags: start_hdfs_datanodes

  - name: service hadoop-hdfs-datanode stop 
    service: name=hadoop-hdfs-datanode
             state=stopped
    tags: stop_hdfs_datanodes

# hosts: r_host
- hosts: r_host
  become: true
  become_user: root
  tasks:

  - name: service rstudio-server start 
    command: rstudio-server start
    tags: start_rstudio_server

  - name: service rstudio-server stop
    command: rstudio-server stop
    tags: stop_rstudio_server
